import React from 'react';
import { motion } from 'framer-motion';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-white rounded-xl shadow-lg p-8"
      >
        <h1 className="text-3xl font-bold mb-8 text-slate-800 border-b pb-4">Privacy Policy</h1>
        <div className="prose max-w-none text-left">
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy Privacy Policy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Effective [Insert Date]</p>
          <p className="mb-4 text-gray-700 leading-relaxed">YOUR PRIVACY IS OUR PRIORITY.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">At ThePawffy (“ThePawffy,” &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), a technology platform provided by Ganapati Rani &amp; Investments LLC, a Texas limited liability company, doing business as ITDesks.co (“ITDesks”), are committed to protecting your privacy and data rights.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">This Privacy Policy explains how we collect, use, share, store, and protect personal and business information related to your use of our platform whether as an individual seeking pet-related services or as a pet service provider. Your rights under applicable U.S. federal and state data protection laws are also described in this policy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We are committed to maintaining transparency and accountability in how we handle your data. Our goal is to provide you with clear, meaningful information so you can make confident, informed decisions about your privacy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Importantly, ThePawffy does not and will not sell your personal data. Our platform’s sole purpose is to facilitate trusted connections between pet owners and verified pet service providers, and not to monetize your identity or information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By accessing or using ThePawffy, you acknowledge that you have read and understood this Privacy Policy and agree to the data practices described herein.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Table of Contents</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Who This Policy Applies To?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Information We Collect</p>
          <p className="mb-4 text-gray-700 leading-relaxed">a. From Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">b. From Vendors</p>
          <p className="mb-4 text-gray-700 leading-relaxed">c. From Both</p>
          <p className="mb-4 text-gray-700 leading-relaxed">How We Collect Your Information?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">How We Use Your Information?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Legal Basis for Processing (for Applicable Regions)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Sharing and Disclosure</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Privacy. We collect, store, and process personal and business-related information in accordance with applicable privacy laws. Your use of the Platform signifies your consent to the collection and use of information as described. We do not sell, rent, or share your personal information, mobile phone number, or SMS opt-in data with any third parties or affiliates for marketing or promotional purposes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Cookies and Tracking Technologies</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your Rights and Choices</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Exercising Your Rights</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Security Measures</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Retention and Deletion</p>
          <p className="mb-4 text-gray-700 leading-relaxed">State Privacy Notice</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Children&#39;s Privacy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Updates To This Privacy Policy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Contact Us</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Who This Policy Applies To?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users: Individuals who use ThePawffy to search for, book, or communicate with pet service providers.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Vendors: Individuals or businesses offering pet-related services through the ThePawffy platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Both: Users and Vendors (anyone who interacts with our platform in a manner that involves the collection or handling of personal information).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Information We Collect</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We collect the following categories of personal, business, and platform-related information to deliver our services, maintain platform integrity, ensure safety and comply with legal obligations:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	From Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Personal Identifiers</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Full name, Email address, phone number, account credentials.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet-Profile Data</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet names, species, age, breed, medical status, uploaded images, preferences for adoption, boarding, or care regarding services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">User-Generated Content</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Reviews, Profile photos, and communication logs.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	From Vendors</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Personal Identifiers</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Full name.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Government-issued identity card or a valid driver’s license (for identity verification purposes).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Date of birth (D.O.B), email address, postal address and phone number.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Account credentials and profile photo also (if submitted).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet-Profile Data</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet names, species, age, breed, medical records or status, uploaded images, videos.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Verification Data</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We collect and retain the following types of verification-related data, where applicable:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. Background check results Information confirming the validity of documents (for example, licenses) and any available records of criminal activity, as provided by our third-party verification partner.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Consent records for verification procedures</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Documentation showing the vendor or user has consented to undergo the verification process.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Identity proofing audit logs</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Logs and audit trails generated during identity verification, which may include timestamped actions and data received from our third-party provider.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Important Note:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy does not charge any fee for background verification services on its platform. All verification procedures are handled by our third-party provider, Checkr, which operates independently.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy facilitates the vendor background check process by initiating a screening request through our third-party provider. Upon initiation, our-third party provider sends the vendor a secure email invitation containing a link to complete the background check directly on their platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Note: Vendors are advised to review the third-party provider’s Privacy Policy to understand how their personal information will be collected, used, and protected during the verification process.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	All background checks, identity proofing, and criminal record screenings are conducted and overseen on the third-party provider’s platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We do not collect or store the documents submitted during this process. We only receive the final outcome—for example, whether a license is valid or if any disqualifying records were found.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Biometric Information</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Our third-party identity verification provider may collect your photo and a copy of your government-issued identity card or driver’s license for identity verification and fraud prevention purposes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Citizenship Status</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your citizenship details may also be collected by our verification partner as required for lawful identity authentication.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">c. From Both</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Location Information</p>
          <p className="mb-4 text-gray-700 leading-relaxed">City/Zip (via IP), GPS (if permitted by device settings).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Device Information, Usage Behavior and Technical Data</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Device Type, IP address, OS version, browser type, referral URL, app activity logs.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Financial and Transactional Data</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Card details (may be stored by third party processors and not ThePawffy).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Transaction records and payment history.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Invoice records and purchase/ booking history.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Communication Logs</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Customer support queries, email interactions, dispute resolution correspondence.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">How We Collect Your Information?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy collects your personal and business information through the following sources and methods.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. Information You Provide Directly</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We collect personal information that you willingly share with us during your interactions on our platform, such as when you:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For Users:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Create or update a user account.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Complete your profile or your pet&#39;s profile.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Post a service request, lost-and-found report, or adoption listing.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Communicate with Vendors or other users via chat or comments.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Submit support tickets, disputes, or platform feedback.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For Vendors:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Submit or update business/service details.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Complete identity verification forms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Upload documents such as licenses, certifications, or insurance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Link payout accounts.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Respond to user requests, disputes, or platform queries.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. Information Collected Automatically</p>
          <p className="mb-4 text-gray-700 leading-relaxed">When you use ThePawffy platform via our mobile app or website, we automatically collect certain technical and usage data using cookies, analytics SDKs, and related technologies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Collected data may include:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Device type, model, and operating system.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Unique device identifier or mobile advertising ID.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Browser type, language settings, screen resolution.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	IP address and geolocation (if permissions are granted).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Session activity (clicks, scrolls, time on page, navigation flow).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Application crash reports, bug diagnostics, and performance logs.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These technologies help us:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Improve platform performance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Detect fraudulent behavior.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Ensure platform security.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Analyze aggregate user behavior (non-personalized).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We do not track your activity outside ThePawffy platform for unrelated purposes. However, for certain services such as pet walking, ThePawffy may collect location data in the background even when the app is not actively in use—strictly for the purpose of enabling and monitoring the service.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users are informed of this location tracking when activating walking services and may withdraw their consent at any time by adjusting their device settings or service preferences.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please note: This data is only used as necessary to provide the service and is never sold or used for unrelated tracking or advertising.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. Information Received from Third Parties</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may collect information about you through trusted third parties in specific scenarios outlined below.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	When you log in using social login options (such as Apple or Google), we receive limited identity details with your authorization.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	If you connect a payment or payout service, we receive confirmation of the transaction from the processor (payment gateway), but we never store full payment credentials.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	If another user reports content associated with your account, we retain the report, the related content, and metadata for moderation, legal, and safety review.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">D. Communication Records</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We retain communication records exchanged through or about our platform to ensure transparency, protect, and comply with legal obligations. These may include:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	In-app messages and conversations (subject to moderation policies).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Emails, push notifications, and SMS notifications.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Inquiries, feedback, or complaints sent through our support services or Help Center.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	User-generated reviews, service ratings, reports, or feedback.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All records are stored securely with restricted access and in accordance with applicable data retention and privacy laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">How We Use Your Information?</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Information from Users and Vendors is utilized to operate the platform efficiently, maintain service quality, introduce improvements, and uphold security standards across ThePawffy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Depending on your role—User or Vendor—certain data is used differently. Below, we’ve detailed how and why your information may be processed:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. Service Fulfillment (Applies to Both)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We process your information to offer key services and ensure seamless interaction within the platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To create, manage, and maintain your ThePawffy account.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To facilitate interactions and transactions between Users and verified Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To personalize your experience based on preferences, location, and pet profile.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To store relevant profile, service, or pet-related data that you voluntarily share.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To match you with relevant services or bookings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To fulfill and confirm service requests or communication threads.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. Communication and Notifications (Applies to Both)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may contact you through in-app messages, emails, or push notifications for legitimate platform-related purposes:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To send booking confirmations, alerts, or updates regarding account activity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To inform you of service status, messages, or transaction confirmations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To respond to inquiries, disputes, feedback, or support tickets.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To provide safety alerts, security changes, or critical account-related notices.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. Legal Compliance &amp; Conformity</p>
          <p className="mb-4 text-gray-700 leading-relaxed">(Applies to Both, with Vendor-Specific Additions)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">The collection and use of specific data are mandated by applicable compliance frameworks and security regulations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For Users:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To detect, investigate, and prevent fraud or misuse of platform features.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To verify identities and pet-related submissions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To comply with subpoenas, legal requests, or dispute resolution processes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To retain evidence where necessary for safety moderation or enforcement.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For Vendors (in addition to above):</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To comply with tax, licensing, insurance, and regulatory obligations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To respond to official inquiries, fraud audits, or investigative requests.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To validate professional identity and ensure lawful service listings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To enforce contractual terms, policies, and dispute decisions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">D. Platform Optimization and Internal Operations (Applies to Both)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We analyze how the platform is used in order to improve its performance, functionality, and optimize the overall user experience.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To monitor technical issues and diagnose bugs.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To review crash logs and analyze system load.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To evaluate service trends and platform features.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To monitor and optimize the usability, layout, and loading speed of the platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To detect unusual activity patterns or repeated errors for system health.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To conduct anonymized analytics and performance testing.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">E. Risk Mitigation &amp; Legal Defense (Applies to Both, with Vendor-Specific Regulatory Emphasis)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We may retain or use certain data to mitigate risk and defend the platform or its participants from legal or safety threats.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To maintain logs of flagged content, chat history, and complaints.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To respond to safety reports or user-submitted violations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To protect ThePawffy, its users, vendors, and third parties from fraud, abuse, or harm.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To uphold our safety protocols and maintain user trust in normal circumstances and in emergencies alike.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	To provide legally defensible records in case of legal claims or internal investigations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">F. Marketing and Promotional Outreach (Applies to Both - Only With Prior Consent)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may offer optional, consent-based communications including:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Platform updates.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Limited-time offers or featured services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Surveys or feedback requests.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Note:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We do not use third-party behavioral advertising or cross-application tracking without your explicit consent. You may opt out at any time.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">G. Contractual and Regulatory Enforcement</p>
          <p className="mb-4 text-gray-700 leading-relaxed">(Applies to Both, with Enhanced Role for Vendors)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To uphold the platform’s operational and legal integrity, we may use your information to:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Implement and monitor adherence to this Privacy Policy and our Terms and Conditions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Ensure compliance with local pet safety, welfare, or service laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Maintain accurate records as required by state veterinary or licensing authorities.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Respond to subpoenas, government inquiries, or lawful discovery processes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Prevent violations of our ethical or platform-specific standards.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Legal Basis for Processing</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy collects, uses, and retains personal information in full compliance with applicable United States federal privacy laws, such as:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Federal Trade Commission Act (FTC Act), the Children’s Online Privacy Protection Act (COPPA), CAN-SPAM Act, Texas Data Privacy and Security Act (TDPSA) and others.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Below is how we legally justify processing your data based on your role on the platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. For Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your data is processed in accordance with these legal foundations:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. With Your Consent</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you provide personal information while creating an account or pet profile.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you voluntarily submit lost/found posts, adoption requests, or service inquiries.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you opt in to receive optional emails, notifications, or promotions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you enable device permissions such as location services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. For Platform Functionality and Service Fulfillment</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To connect you with verified vendors on our platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To process bookings, deliver chat functionality, and allow profile management.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To maintain service records and ensure relevant pet details are visible when you choose to share them.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. To Protect Against Fraud and Misuse</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To detect suspicious activity and monitor for policy violations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To verify the legitimacy of user activity and flag abuse reports.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To enforce our Terms and Conditions and maintain platform integrity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. To Comply with Legal Requirements</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When we are legally required to retain data (such as for dispute resolution).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To address and fulfill obligations arising from subpoenas, regulatory investigations, or legally binding court rulings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To assist authorities in preventing fraud or harm, when required by law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. For Vendors</p>
          <p className="mb-4 text-gray-700 leading-relaxed">As a Vendor, your use of ThePawffy may involve additional data collection based on your business services. We process your data under these legal grounds:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. With Your Consent</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you submit business details, licenses etc.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you voluntarily link payout accounts or authorize background checks.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– When you enroll in optional promotional programs or visibility enhancements.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. To Fulfill Your Use of the Platform</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To create and manage your vendor profile and listings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To facilitate service requests and communication with pet owners.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To calculate and issue payments, apply platform fees, and maintain tax records.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. To Ensure Platform Security and Trust</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To verify your identity and legitimacy as a service provider.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To protect users from fraudulent listings or unsafe services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To evaluate and respond to any claims involving inappropriate behavior, safety risks, or failure to comply with our policies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. To Comply with Legal and Regulatory Requirements</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– We limit data disclosure to situations involving legal compliance, contractual duties, or security needs.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To support IRS reporting obligations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To respond to subpoenas, official investigations, or law enforcement actions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. For Both</p>
          <p className="mb-4 text-gray-700 leading-relaxed">The following legal bases apply across both groups when necessary:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. To Protect Safety and Prevent Harm</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– In the event of emergencies involving pets, users, or public safety.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To coordinate with animal welfare authorities, law enforcement, or medical professionals as permitted by law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. To Resolve Dispute and Maintain Platform Integrity</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To preserve chat logs, reviews, or reports for resolving platform complaints.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To provide legally defensible documentation in case of disputes or claims.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">– To enforce our Terms &amp; Conditions (link) and internal content policies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Sharing and Disclosure</p>
          <p className="mb-4 text-gray-700 leading-relaxed">At ThePawffy, we are committed to protecting your personal and business information. We do not sell or lease any user or vendor data to third parties. Disclosure of information is limited to situations involving legal compliance, contractual requirements, or essential security measures.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. When Disclosure May Occur</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your information may be shared in accordance with the legal bases outlined below:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. To deliver and maintain platform functionality.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. To fulfill legitimate service interactions or contractual obligations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. To comply with U.S. law or protect platform integrity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. To prevent fraud, abuse, or safety threats.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5. To support a corporate merger, acquisition, or restructuring (with notice).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. For Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may share limited personal data with:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Third-Party Payment Processors: (payment gateways), cloud infrastructure and hosting partners, customer support systems.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Vendors You Engage With:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Only essential data—such as your pet profile, service requests, or booking details—is shared and only when you initiate or agree to an interaction.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Regulatory or Legal Authorities:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">When required to comply with subpoenas, court orders, or legal processes and to protect your rights, platform security, or public safety.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In Corporate Transactions:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In case of a business acquisition or restructuring, provided data privacy protections remain intact and users are informed in advance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. For Vendors (Pet Service Providers)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may share your business and operational data in the following cases:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">With Users:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Business name, services offered, public photos, ratings, location, and other content submitted for visibility will be publicly shown to users.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">With Authorized Third-Party Service Providers:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Under strict data processing agreements, we may share your information with partners who assist with:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Identity and background verification.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Secure payment and payout processing.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Tax reporting and form submissions</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Cloud storage and infrastructure.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Help Center and customer communication tools.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">With Legal and Regulatory Authorities:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	When required by tax, financial, or public safety laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	In case of fraud, criminal investigations, or court orders.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">With Internal Compliance Teams:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For audits, platform investigations, or enforcement of our Terms and Conditions(link).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">During Corporate Restructuring:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your data may be transferred to an acquiring party, under equivalent or stronger privacy protection terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Cookies and Tracking Technologies</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy uses cookies and similar technologies (“Cookies”) strictly for platform performance, security, and analytics. We do not use third-party behavioral tracking without your consent.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. Technologies Used by ThePawffy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Necessary Cookies</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Used for essential features like login authentication and site navigation.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Performance &amp; Analytics Cookies</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Help us understand how users engage with the platform (including, time spent, errors, feature use).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Security Technologies</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Detect suspicious patterns, monitor abuse, and prevent misuse of services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. Your Choices</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You can manage cookie preferences via browser settings or disable non-essential cookies (where available) through in-app controls.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">On mobile devices, permissions (e.g., location, camera) can be managed in device settings. However, disabling certain cookies may affect platform functionality.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your Rights Your Choices</p>
          <p className="mb-4 text-gray-700 leading-relaxed">As a resident of California, you are granted specific rights under both federal and state privacy laws, including the California Consumer Privacy Act (CCPA) and its amendment, the California Privacy Rights Act (CPRA). These rights provide you with clear authority over your personal information, including the right to know what data is collected, request access, correct inaccuracies, and request deletion, subject to applicable limitations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">At ThePawffy, we are committed to honoring these rights and ensuring that you have transparent and accessible options to manage how your personal data is used, disclosed, and retained.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. Right to Know</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You have the right to obtain a report detailing the personal or business information collected, used, disclosed, or retained about you during the past 12 months.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Right to Access</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may access your account data, profile details, transaction history, or service listings associated with your profile at any time.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Right to Correct</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You can request correction of inaccurate, outdated, or incomplete information related to your user or vendor account.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. Right to Delete</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may request deletion of your data, subject to legal and operational retention requirements (e.g., fraud prevention, tax reporting).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5. Right to Limit the Use of Sensitive Information</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You can request restriction on the use of sensitive data such as geolocation, identification documents when such data is not essential to delivering platform services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6. Right to Opt Out of Data Disclosure</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You have the right to refuse the sale or sharing of your personal information for cross-context behavioral advertising or targeted marketing.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may allow third-party tools to collect limited data (such as, IP address, location, or device ID) using cookies. You can opt out via: Our Privacy Management Center(link).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">7. Right to Appeal</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In case your privacy request is denied, you have the right to appeal the decision. We will evaluate your appeal and provide a written explanation of our final determination.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">8. Right to Non-Discrimination</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You will not be denied access, penalized, or treated unfairly for exercising your privacy rights. Your experience on the platform will remain fully available regardless of your data preferences.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Exercising Your Rights</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If you wish to exercise your rights,</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Please visit our Help Center (Link), our Privacy Management Center.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Email our Data Protection Officer directly.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Submit a formal request via the in-app Help Center or Contact Form.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Security Measures</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We take data protection seriously and implement both technical and administrative safeguards to prevent unauthorized access, misuse, alteration, or destruction of user and vendor data.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. Technical Safeguards</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. End-to-end encryption of sensitive data (including payment info, IDs, tax documents).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Role-specific access permissions, allowing only approved team members to access sensitive records.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Regular security assessments and timely system updates.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. Secure integration with pre-vetted third-party services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. Administrative Safeguards</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. Mandatory background checks for staff with elevated data access.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. All interactions with sensitive records are recorded and reviewed regularly to detect misuse or unauthorized activity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Required data handling and privacy training for relevant teams.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. Breach detection and incident response protocols in place.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. User Responsibilities (Applies to Both)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users are equally responsible for safeguarding their accounts.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You must:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. Keep your login credentials confidential.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Notify us immediately if any unauthorized activity or breach is suspected.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Data Retention and Deletion</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy retains personal and business data only for as long as necessary to fulfill business, legal, and regulatory requirements. Retention durations are tailored to the specific type of data and are guided by legal mandates and operational necessity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. For Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet Profiles, Messages, and Reviews:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained until you delete your account or request removal.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Booking and Transaction History: Retained to ensure service history is available and secure.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Dispute or Safety Reports:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained For legal defense and moderation integrity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Support Records:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained as necessary for quality assurance and safety compliance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. For Vendors</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Identity &amp; Verification Documents:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained as long as reasonably necessary for fraud prevention, compliance, and audits.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Payment &amp; Transaction Records:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained for tax reporting, dispute resolution, and regulatory compliance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Business Listings &amp; Ratings:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained unless the vendor account is closed and deletion is legally permitted.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Support Messages &amp; Internal Logs:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Retained for operational auditing and compliance reviews.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. Account Deletion Requests</p>
          <p className="mb-4 text-gray-700 leading-relaxed">When a deletion request is submitted:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. Your account is deactivated from public view.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Non-essential data is deleted or anonymized.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Information required for tax, fraud prevention, or legal compliance is retained in accordance with applicable law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">State Privacy Notice</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Residents of certain U.S. states including California, Colorado, Connecticut, Delaware, Iowa, Indiana, Montana, Minnesota, Nevada, New Jersey, Oregon, Tennessee, Texas, Utah, Virginia, and any other state with applicable privacy laws may have additional rights regarding their personal data.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Depending on your state law, you may have the right to:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Request access to, or deletion of, the personal information we have collected about you.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Correct inaccurate personal information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Choose not to allow your data to be used for behavioral advertising, user profiling, or any form of sale or disclosure.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Appeal any decision we make about your privacy request.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Identity verification is required before we act on any request. We aim to respond within 45 calendar days, but this period may be extended once by up to an additional 45 days, provided we notify you in advance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. Deletion Rights and Exceptions</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may submit a request for deletion of your personal data at any time by contacting us at [email].</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We aim to fulfill lawful data deletion requests within 45 days, unless prevented by specific legal or operational reasons outlined below:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We are legally required to retain certain information (such as for law enforcement or regulatory filings).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Retention is required to process an active service request or to resolve a matter that remains under dispute.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Retaining the data is necessary to prevent fraud, abuse, or repeat violations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">C. User-Generated Content Deletion</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If you delete your account, the following will apply to your public content:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users: Your pet profiles, reviews, service requests, comments, and any other visible content will be removed from public view.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Vendors: Your service listings, business descriptions, reviews received, ratings, and public profile details will be hidden or removed from the platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">However, ThePawffy may retain internal archival copies of user- or vendor-generated content in accordance with applicable federal and state laws, including for:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Legal compliance</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Fraud prevention</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Dispute resolution</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Regulatory or tax obligations</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Such archival retention will never include public redistribution or republishing and will be limited to what is lawfully required or contractually permitted, up to as long as reasonably necessary.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Children&#39;s Privacy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy is committed to protecting the privacy and safety of minors across the platform and adheres to all applicable U.S. child privacy and protection laws, including the Children’s Online Privacy Protection Act (COPPA) and relevant contract eligibility standards.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A. For Users</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy is not intended for children under the age of 13, and we do not knowingly collect, store, or process personal information from individuals in this age group. In compliance with COPPA:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Any account found to be created or operated by someone under 13 will be deleted upon discovery.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users aged 13 to 17 may access the platform only with the verifiable consent and direct supervision of a parent or legal guardian, who assumes full responsibility for the account&#39;s activity and compliance with our Terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Only individuals aged 18 and above may independently use the full range of services or enter into any contractual or transactional relationship on ThePawffy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">B. For Vendors</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy vendor platform is strictly intended for individuals who are 18 years of age or older. Vendors must meet the following eligibility criteria:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Be at least 18 years old.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Be legally capable of entering into binding contracts under U.S. law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Not submit vendor profiles, business listings, or legal documentation on behalf of or for use by any minor.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We do not knowingly accept, verify, or process vendor data submitted by or for individuals under 18. If we identify any such account, it will be promptly disabled, and all related data will be permanently deleted, except where retention is required by law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	In addition, vendors must ensure that their services are not designed for, targeted toward, or provided to minors in a way that violates applicable child protection laws. All vendor listings and activities must comply with platform policies and U.S. regulations governing services involving minors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To report unauthorized use by a minor, please contact us at [email]. We will investigate and act promptly.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Changes to Privacy Policy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy may update this Privacy Policy to reflect changes in legal requirements, technology, or our business operations from time to time.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy will send notification of updates if material changes were done regarding how we collect, use, or share your data, we will notify you through the email (link), or prominent notice within the user dashboard or ThePawffy app.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All changes become effective on the date mentioned at the top of this Privacy Policy. Use of the platform after the changes take effect signifies your acknowledgment and acceptance of the updated Policy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please review this Privacy Policy regularly to stay informed of how your data is handled or in case of any updates regarding this policy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Contact Us</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If you have any questions, concerns, or complaints about this Privacy Policy, or if you would like to exercise your privacy rights, you can contact us through the following channels:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy Privacy Office</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Email: [Insert]</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Help Center: Accessible via ThePawffy mobile app or website under “Support”</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Mailing Address: [Insert]</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please note: We may be required to verify your identity to a degree of certainty before proceeding with your request.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We will address the concerns promptly, respectfully, and in accordance with all applicable laws.</p>
        </div>
      </motion.div>
    </div>
  );
};

export default PrivacyPolicy;
