import React from 'react';
import { motion } from 'framer-motion';

const TermsVendors = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-white rounded-xl shadow-lg p-8"
      >
        <h1 className="text-3xl font-bold mb-8 text-slate-800 border-b pb-4">Terms Vendors</h1>
        <div className="prose max-w-none text-left">
          <p className="mb-4 text-gray-700 leading-relaxed">Terms and Conditions</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Effective [Insert Date]</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Welcome to ThePawffy. These Terms and Conditions (“Terms”) are a legally binding agreement between you (“you” or “Vendor”) and ThePawffy (“ThePawffy,” “Company,” “we,” “us,” or “our”). These Terms set the rules for using the Platform to offer pet-related services to users (&quot;Users&quot;) via our website, mobile app, or related systems (collectively, the “Platform”).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">SECTION 18 OF THESE TERMS CONTAINS AN ARBITRATION CLAUSE AFFECTING YOUR LEGAL RIGHTS. PLEASE READ IT CAREFULLY.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please review our Privacy Policy which also governs your use of our Platform along with these Terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By continuing to use or access this Platform, you agree that you have read, understood, and accepted these Terms. If you disagree with these Terms, YOU SHOULD NOT USE THE PLATFORM.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy&#39;s Role</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Eligibility</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Account Registration</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Account Verification</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Vendor Content</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Platform Fee and Withdrawal Terms</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Vaccination Requirements and Pet Refusal</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Cancellations</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Emergency Protocol</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Third-Party Services, Links.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Account Security</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Privacy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Vendor Representation and Warranties</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Disclaimer of Warranties</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Limitation of Liability</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Indemnity</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Review and Feedback Policy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Governing Law and Dispute Resolution</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Texas Vendor Compliance Notice</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Class Action Waiver</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	General</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The Pawffy’s Right to Content and Technology</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Independent Vendor Disclaimer</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Copyright Infringement and Notice</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 No Copyright Licence or Waiver</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Modifications</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Severability</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Entire Agreement</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 Contact Information</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. ThePawffy&#39;s Role.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy is a technology Platform operated by Ganapati Rani &amp; Investments LLC, a Texas limited liability company doing business as ITDesks.co (“ITDesks”). The Platform’s sole purpose is to connect independent Vendors (pet service providers such as training, walking, grooming, veterinary, etc) with individuals seeking pet-related services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Any service booked through our Platform is fulfilled solely by third-party vendors who are not employees, agents, or affiliates of ThePawffy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy does not supervise, manage, employ, or control the vendors or the services they provide. As a Vendor offering services through the Platform, you confirm that you are operating as an independent contractor. These Terms do not create, and shall not be interpreted as creating, any employment, agency, partnership, joint venture, or other legal affiliation between you and ThePawffy or ITDesks. You are not authorized to represent or act on behalf of ThePawffy or ITDesks in any capacity and you may not bind the company in any form.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Eligibility.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By using or accessing ThePawffy, you confirm that you are at least 18 years old and are legally eligible to enter into binding agreements.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please Note: Individuals previously banned or removed from ThePawffy may not register or offer services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Account Registration.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All Vendors must register using accurate and current information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. Account Verification.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To access and use ThePawffy Platform as a vendor, you must complete an identity and background verification process conducted by our third-party provider. While ThePawffy does not charge any fee for this service, a non-refundable verification fee may be required by the third-party provider, which is collected by them directly at the time of registration. By registering as a vendor, you agree to this verification requirement and any applicable third-party fees.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please Note. ThePawffy reserves the right to deny access or suspend accounts in cases of:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Failed verification,</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Suspected fraud, or</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Inaccurate disclosures.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5. Vendor Content.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We may require or allow you to submit or upload certain materials to the Platform, including but not limited to text, images, service descriptions, pricing details, policies, and other content related to your offerings (‘Vendor Content’). Submission of the Vendor Content confirms that:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The information is correct,</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	It does not violate any laws,</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	You hold all necessary rights and permissions required to use and share it on the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.1 Service Listings and Engagements.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">As a Vendor, you must keep your listings accurate and updated, including details about pricing, availability, policies, and the scope of services you offer. When you accept a booking, you must agree to deliver the services as described.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.2 Vendor Conduct and Safety.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">As a vendor, you&#39;re expected to:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Conduct services offered on the Platform in a professional, safe, and respectful manner.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Avoid any abusive, dishonest, discriminatory, and against the law actions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Abide by your posted policies and service terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Prioritize all pets safety and well-being in your care.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Not engage in off-platform transactions or unauthorized solicitations. (The Platform won&#39;t be held liable for any off-platform transactions and in incidents.)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Violations regarding these may result in account suspension or legal action.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.3 License to Use.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By submitting Vendor Content, you grant ThePawffy and its affiliates a non-exclusive, royalty-free, worldwide license to use, display, host, modify (for formatting purposes), reproduce, and distribute such content solely in connection with the operation, promotion, or improvement of the Platform and its services. This license remains in effect until your content is removed from the Platform, except where copies have already been previously used or lawfully archieved.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.4 Content Monitoring and Removal.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy reserves the right but is not obligated to monitor, screen, edit, or remove any Vendor Content at its sole discretion if it violates these Terms, appears unlawful, or undermines the safety, integrity, or reputation of the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.5 No Endorsement.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You understand and agree that your presence on the Platform does not imply any endorsement, verification, or guarantee by ThePawffy or ITDesks. Your listing, reviews, or visibility on the Platform do not represent approval or certification by ThePawffy, and you remain solely responsible for your services, qualifications, and interactions with Users.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5.6 Release.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By submitting content including your name, image, voice, likeness, or performance, you grant ThePawffy, ITDesks, and their affiliates the right to use it for Platform-related marketing, promotion, and operations. This includes public use across digital and print channels.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To the extent allowed by law, you hereby waive any claims against ThePawffy, ITDesks, and authorized third parties for such use, including claims involving privacy, defamation, or publicity rights.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6. Platform Fees and Withdrawal Terms</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.1 Subscription Plans.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Vendors must subscribe to one of the following monthly plans to access payment withdrawal features on the Platform:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Single-Role Partners: Vendors offering only one type of service (such as grooming or boarding) may choose from the following two options:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Partner Single Basic – $19.99/month</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Maximum of two (2) withdrawals per month.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Minimum withdrawal amount: $200.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Partner Single Premium – $29.99/month</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Unlimited withdrawals per month.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Minimum withdrawal amount: $150.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Multi-Role Partners: Vendors offering more than one type of service (such as grooming and boarding) must subscribe to the following plan:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Partner Multi Premium – $19.99/month per service role</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Unlimited withdrawals per month.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Minimum withdrawal amount: $150.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.2 Vendor Withdrawals.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Vendors may request a withdrawal of their earnings through the platform’s dashboard.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy will acknowledge and approve such requests within 24 hours.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Payouts will be processed and credited to the Vendor’s chosen payment method within seven (7) calendar days of approval. Transaction and processing fees may apply.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	This timeline applies uniformly across all subscription plans and is part of the Platform’s standard payout process.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Applicable transaction fees may be deducted. You are fully responsible for any issues arising from inaccurate or outdated payment information provided on the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy has the right to do modifications in its fee structure at any time, with advance prior notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Vendors are solely responsible for managing and reporting their own income, as well as complying with all applicable tax obligations</p>
          <p className="mb-4 text-gray-700 leading-relaxed">7. Vaccination Proof and Pet Refusal.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may require Pet Owners to provide proof of vaccinations before service. If a pet appears aggressive, unwell, or unfit for care, you may refuse service in accordance with your stated policy. ThePawffy is not liable for any incidents resulting from pet health issues or misrepresentations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">8. Cancellations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Upon any cancellations, a Vendor should notify the Users immediately. Repeated cancellations negatively impact your account status, including lowered visibility or even account termination.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy may intervene in disputes but is not obligated to mediate.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">9. Emergency Protocol.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In the event of a pet emergency, you must:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Attempt to contact the Pet Owner immediately;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	If unreachable, contact ThePawffy’s Help Center;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	 And seek veterinary care if necessary.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Pet Owners (Users) are financially responsible for emergency costs. You further agree to respond responsibly and in a good faith manner during such emergency situations.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">10. Third-Party Services, Links.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">The Platform may provide access to or rely on services operated by third parties, including but not limited to payment processors, veterinary directories, mapping integrations, and verification partners. These services are not controlled by ThePawffy and you acknowledge and agree that:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Third-party tools or services are subjected to their own usage terms and data policies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The Platform does not endorse, monitor, or guarantee the availability, accuracy, security, or performance of such third-party offerings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Use of third-party tools is at your responsibility. The Platform is not responsible for their performance or outcomes, losses, damages, or any issues arising from your interactions with or reliance on third-party providers.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">11. Account Security.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You must keep your login details confidential and notify us immediately in case of any suspicious unauthorized access or data compromise.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">12. Privacy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We collect, store, and process personal and business related information in accordance with applicable privacy laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Please refer to our Privacy Policy to learn more.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Your use of the Platform signifies your consent to the collection and use of information as described.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">13. Vendor Representations and Warranties.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">As a vendor, you represent and warrant that you:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Are legally authorized to offer the services listed on the Platform;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Hold all necessary licenses, permits, and insurance required by law;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	provided Information on the Platform is accurate and current;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Agree to deliver services in a professional, safe, and ethically responsible manner;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Comply with all governing laws and regulatory requirements;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Acknowledge that non-compliance with these obligations may result in immediate suspension or termination of your account, without advance notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">14. Disclaimer of Warranties.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">THE PLATFORM, INCLUDING ALL FEATURES AND SERVICES, IS OFFERED WITHOUT ANY GUARANTEES OR PROMISES OF ANY KIND. TO THE EXTENT PERMITTED BY LAW, ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES ARE DISCLAIMED, INCLUDING ANY WARRANTIES OF PERFORMANCE, FITNESS, MERCHANTABILITY, OR NON-INFRINGEMENT.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">15. Limitation of Liability.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To the maximum extent permitted under applicable law, ThePawffy shall not be held liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, including, without limitation, damages for loss of profits, data, goodwill, or other intangible losses, arising out of or in connection with your use of the Platform or the services provided.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In no case shall ThePawffy’s total cumulative liability to you exceed the total amount of fees, if any, that you paid to ThePawffy in the twelve (12) months prior to the event that gave rise to the claim.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">16. Indemnity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You agree to indemnify, defend, and hold harmless ThePawffy, its parent entity, affiliates, officers, directors, employees, and representatives from any legal actions, third-party claims, damages, fines, or other financial burdens that may arise in connection with:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Your use of the Platform as a vendor;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Any services you provide to Users;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Your failure to comply with applicable laws, regulatory requirements, or the rights of third parties;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Any breach of these Terms or your representations herein.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">17. Review and Feedback Policy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">The Platform may allow users to leave reviews or ratings regarding vendor services. Your use of the Platform confirms that you acknowledge and agree to the following:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy reserves the right to display, moderate, filter, or remove reviews at its sole discretion.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	You shall not manipulate, falsify, incentivize, or suppress user feedback.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Retaliation against users for providing reviews is strictly prohibited.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	You may respond to reviews professionally and respectfully but not demand changes from users.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Reviews do not reflect ThePawffy’s views and are the sole opinions of the User.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy is not liable for the content or consequences of such feedback.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">18. Governing Law and Dispute Resolution.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms, and any dispute, claim, or controversy arising out of or relating to your role as a vendor on ThePawffy Platform, including but not limited to registration, use of services, content submissions, payments, or performance of services shall be governed by and construed in accordance with the laws of the State of Texas, without regard to any conflict of law provisions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Prior to initiating formal proceedings, both you and ThePawffy agree to first attempt in good faith to resolve any dispute through informal discussions. If such discussions fail to resolve the matter within thirty (30) days, the dispute shall be resolved exclusively through final and binding arbitration administered by a nationally recognized arbitration provider in accordance with its then-current Commercial Arbitration Rules.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Arbitration shall be conducted in Harris County, Texas, before a single impartial arbitrator. The arbitrator’s decision will be final and binding on both parties and may be enforced in any court having appropriate jurisdiction.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By agreeing to these Terms, you and ThePawffy expressly waive the right to a jury trial and agree that any arbitration shall proceed solely on an individual basis. You further waive any right to participate in a class action, class arbitration, or any consolidated or representative proceeding of any kind.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">This does not preclude either party from seeking emergency or equitable relief in a court of competent jurisdiction to prevent immediate or irreparable harm.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">19. Class Action Waiver.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You agree to resolve any dispute with ThePawffy or ITDesks solely on an individual basis. You agree not to pursue or participate in any class, group, or representative action whether in court or arbitration. Any claim must be pursued separately and may not be combined with those of other individuals.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">20. Notice to the Texas Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If you reside in, operate from, or provide services within Texas, you acknowledge that all activities conducted through ThePawffy are considered to occur within the State of Texas for legal and regulatory purposes. Any dispute arising from your Vendor use of the Platform will be governed by Texas law and subject to the arbitration terms in Section 18. You also agree to the jurisdiction of the courts in Harris County, Texas, for enforcing arbitration outcomes or injunctive relief, and hereby waive any objections related to venue.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">21. General.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy may, at its discretion, help facilitate communication or assist with dispute resolution between Users and Vendors. However, ThePawffy is under no obligation to mediate, issue refunds, or enforce Vendor policies unless required by applicable law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">22. The Pawffy’s Right to Content and Technology.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All content, branding elements, features, and technology made available through ThePawffy are the sole property of ThePawffy and are protected under applicable U.S. laws. Use of the Platform’s features, code, or content without our written approval, including copying, altering, or reverse engineering is strictly prohibited</p>
          <p className="mb-4 text-gray-700 leading-relaxed">23. Independent Vendor Disclaimer.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy does not endorse or guarantee any Vendor, Pet Owner, service quality, safety, or compatibility. Background checks are performed to the extent allowed by law but do not replace personal vetting.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">24. Copyright Infringement and Notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy respects the proprietary rights of others and expects all vendors who use and access our platform to do the same. If you believe your copyrighted material has been used on the Platform without permission, you must submit a written notice that includes:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Your full name</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Contact information;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A description of the copyrighted work in question;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A clear reference to the allegedly infringing content and its location on the Platform;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A statement that you believe with certainty, the use is unauthorized;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A legally binding declaration, under penalty of perjury, confirming the accuracy of your claim and your authority to represent the owner of the rights;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A physical or electronic signature from you or your authorized representative</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To send DMCA Notice, contact us at:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">(Email)</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy Legal Compliance Team [Insert full mailing address]</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy complies with the DMCA and responds in a timely manner to verified takedown requests.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">25. No Copyright License or Waiver.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Nothing in these Terms shall be interpreted as granting any license or right to use any proprietary materials of ThePawffy or its licensors except as expressly provided. Any unauthorized use of such materials may result in suspension or termination of access to the Platform, and may be prosecuted under applicable law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">26. Modifications.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms may be revised periodically, and your continued use of the Platform, signifies your acceptance of any changes. Updates will be posted with the revised effective date. Material changes will be notified through email or in-app notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By continuing to use the platform, you acknowledge and accept these Terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">27. Severability.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If any provision of these Terms is determined to be invalid, illegal, or unenforceable under applicable law, that provision shall be modified or limited to the extent necessary to make it enforceable. The remainder of these Terms will remain valid and in full effect.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">28. Entire Agreement.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms, along with our Privacy Policy, represent the entire understanding between you and ThePawffy. No oral or written statements outside these documents will alter or modify them unless in writing and signed by both parties.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">29. Contact Information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For legal notices or questions, contact us at:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">(Phone Number) legal@thepawffyapp.com ThePawffy Legal Compliance Team</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Address: 5900 Balcones Drive</p>
          <p className="mb-4 text-gray-700 leading-relaxed">STE</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Austin, TX 78731</p>
        </div>
      </motion.div>
    </div>
  );
};

export default TermsVendors;
