import React from 'react';
import { motion } from 'framer-motion';

const TermsUsers = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-white rounded-xl shadow-lg p-8"
      >
        <h1 className="text-3xl font-bold mb-8 text-slate-800 border-b pb-4">Terms Users</h1>
        <div className="prose max-w-none text-left">
          <p className="mb-4 text-gray-700 leading-relaxed">Terms and Conditions</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Effective September 29, 2026</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Welcome to ThePawffy. These Terms and Conditions (“Terms”) are a legally binding agreement between you (“you” or “User”) and ThePawffy (“ThePawffy,” “Company,” “we,” “us,” or “our”).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms set the rules for accessing or using ThePawffy’s services through our website, mobile application, or associated platforms (collectively, the &quot;Platform&quot;).</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By using or accessing the Platform, you agree that you have read, understood, and accepted these Terms. If you disagree with these Terms, YOU SHOULD NOT USE THE PLATFORM.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Links to be added of these sections</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. ThePawffy&#39;s Role</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Eligibility</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Account Registration</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. User Content</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4.1 License</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4.2 Release</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5. Pet Health and Vaccination Requirements</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6. Platform Fees &amp; Charges</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.1 Platform Fee</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.2 Pricing Transparency</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.3 Non-Refundable</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.4 Taxes</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.5 Changes to Fees</p>
          <p className="mb-4 text-gray-700 leading-relaxed">7. Booking and Payments</p>
          <p className="mb-4 text-gray-700 leading-relaxed">8. Cancellation and Refunds</p>
          <p className="mb-4 text-gray-700 leading-relaxed">9. Emergency Protocols</p>
          <p className="mb-4 text-gray-700 leading-relaxed">10. Third-Party Services, Links</p>
          <p className="mb-4 text-gray-700 leading-relaxed">11. Account Security</p>
          <p className="mb-4 text-gray-700 leading-relaxed">12. Privacy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">13. Risk Disclaimers</p>
          <p className="mb-4 text-gray-700 leading-relaxed">14. User Conduct Standards</p>
          <p className="mb-4 text-gray-700 leading-relaxed">15. Disclaimer of Warranties</p>
          <p className="mb-4 text-gray-700 leading-relaxed">16. Limitation of Liability</p>
          <p className="mb-4 text-gray-700 leading-relaxed">17. Indemnity</p>
          <p className="mb-4 text-gray-700 leading-relaxed">18. Reviews and Feedback Policy</p>
          <p className="mb-4 text-gray-700 leading-relaxed">19. Governing Law and Dispute Resolution</p>
          <p className="mb-4 text-gray-700 leading-relaxed">20. Notice to Texas Residents</p>
          <p className="mb-4 text-gray-700 leading-relaxed">21. Class Action Waiver</p>
          <p className="mb-4 text-gray-700 leading-relaxed">22. General</p>
          <p className="mb-4 text-gray-700 leading-relaxed">23. Copyright Infringement and Notice</p>
          <p className="mb-4 text-gray-700 leading-relaxed">24. No Copyright License or Waiver</p>
          <p className="mb-4 text-gray-700 leading-relaxed">25. The Pawffy’s Right to Content and Technology</p>
          <p className="mb-4 text-gray-700 leading-relaxed">26. Modifications</p>
          <p className="mb-4 text-gray-700 leading-relaxed">27. Severability</p>
          <p className="mb-4 text-gray-700 leading-relaxed">28. Entire Agreement</p>
          <p className="mb-4 text-gray-700 leading-relaxed">29. Contact Information</p>
          <p className="mb-4 text-gray-700 leading-relaxed">1. ThePawffy&#39;s Role.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy is a technology Platform operated by Ganapati Rani &amp; Investments LLC, a Texas limited liability company doing business as ITDesks.co (“ITDesks”). The sole purpose of Pawffy is to connect Pet Owners (&quot;Users&quot;) with independent third-party service providers (&quot;Vendors&quot;) offering pet care and related services. ThePawffy does not offer, control, supervise, or assume responsibility for any services provided by Vendors. All bookings, services, and interactions occur directly between Users and Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms confirm that ThePawffy operates solely as a Platform and is not a contractual party to any service agreements made through it.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">2. Eligibility.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By using or accessing ThePawffy, you confirm that you are at least 18 years old and are legally eligible to enter into binding agreements.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">3. Account Registration.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To create your account on ThePawffy, you must provide accurate and complete information. Creating an account on the Platform using false or misleading information may lead to account suspension or legal action.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4. User Content.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may submit or upload content to the Platform, including but not limited to pet profiles, reviews, photos, videos, feedback, messages, and other material (“User Content”). By submitting such content, you hereby grant ThePawffy a perpetual, worldwide, non-exclusive, royalty-free, transferable, and sublicensable license to use, host, store, reproduce, modify, adapt, publish, translate, distribute, publicly display, and create derivative works from your User Content in connection with the operation, marketing, and improvement of the Platform and our services.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4.1 License</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You acknowledge and agree that ThePawffy may, at its sole discretion, use your User Content in public-facing materials, including but not limited to promotional campaigns, social media, advertising, testimonials, newsletters, blog articles, or case studies, with or without credit or attribution. If you do not wish to grant such promotional rights, you must notify us in writing at the contact information provided later in these Terms. By submitting User Content, you represent and warrant that:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	You own all necessary rights to the content;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The content is accurate and not misleading;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The content usage does not violate any third-party rights;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The content follows these Terms and adheres to all governing laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy does not endorse any User Content and expressly disclaims any liability arising from it. We reserve the right (but not the obligation) to review, remove, edit, or disable any User Content, in whole or in part, at our discretion and without notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">4.2 Release</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By submitting User Content, you grant ThePawffy, ITDesks, and their affiliates the right to use, display, and distribute it in connection with the Platform’s operation, marketing, and promotional efforts. This includes public use across digital and print channels.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To the extent allowed by law, you waive any claims against ThePawffy, ITDesks, and authorized third parties for such use, including claims involving privacy, defamation, or publicity rights.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">5. Pet Health and Vaccination Requirements.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You are required as a User to ensure that your pet is healthy, well-behaved, and vaccinated before any service engagement. Vendors may require documentation or proof of vaccination prior to accepting a booking.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy shall not be held liable for any illness, injury, or incident arising from inaccurate pet health disclosures or lack of vaccination compliance.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6. Platform Fees &amp; Charges.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Use of certain features on ThePawffy may require payment of a platform usage fee. This fee supports the maintenance, development, and enhancement of our platform and services. Your use of the Platform confirms that you agree to the outlined conditions below:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.1 Platform Fee</p>
          <p className="mb-4 text-gray-700 leading-relaxed">A non-refundable Platform usage fee of [insert here] may be charged per transaction. This fee will be clearly disclosed at the time of booking or transaction.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.2 Pricing Transparency</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All applicable platform fees will be displayed prior to confirming any transaction or booking. You will have the opportunity to review the total amount, including applicable service or vendor fees, before proceeding.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.3 Non-Refundable</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Platform usage fees in any case are non-refundable unless required by law, as they are charged for facilitating and maintaining the Platform service.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.4 Taxes</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Where applicable, taxes may be added to the Platform fee as required by applicable laws.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">6.5 Changes to Fees</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy reserves the right to modify its Platform fee structure at any time. Any changes will be communicated through updates to these Terms or via platform notifications. Continued use of the Platform following such changes constitutes your acceptance of the new fee structure.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">7. Booking and Payments.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All bookings must be made through the Platform. Off-platform payments or service arrangements are strictly prohibited. The Platform won&#39;t be held liable for any off-platform transactions and in case of any incidents.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Payments are processed by third-party providers. You authorize all applicable service fees, processing charges, and payment holds necessary for transaction security. ThePawffy may implement temporary holds on funds to ensure service completion or resolve disputes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">8. Cancellation and Refunds.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Cancellations and refunds are governed by the Vendor’s individual cancellation policy, displayed on the Vendor’s profile and during checkout. ThePawffy is not responsible for enforcing Vendor policies unless legally required. Refunds may be subject to transaction delays, administrative reviews, and processing timeframes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">9. Emergency Protocols.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">In the event of a medical or safety emergency involving your pet, the Vendor will make reasonable efforts to contact you immediately. If you are unreachable, the Vendor may contact ThePawffy&#39;s emergency support team and, if necessary, arrange for emergency veterinary care. By using the Platform, you expressly authorize such action and agree to be fully responsible for any resulting veterinary or emergency service costs. ThePawffy does not assume responsibility for medical outcomes or decisions made during emergencies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">10. Third-Party Services, Links.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">The Platform may provide access to or rely on services operated by third parties, including but not limited to payment processors, veterinary directories, mapping integrations, and verification partners. These services are not controlled by ThePawffy and you acknowledge and agree that:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Third-party tools or services are subjected to their own usage terms and data policies.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	The Platform does not endorse, monitor, or guarantee the availability, accuracy, security, or performance of such third-party offerings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Use of third-party tools is at your responsibility. The Platform is not responsible for their performance or outcomes, losses, damages, or any issues arising from your interactions with or reliance on third-party providers.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">11. Account Security.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You must keep your login details confidential and notify us immediately in case of any unauthorized access or compromise of your account data.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We reserve the right to suspend or terminate accounts at our discretion, particularly in cases of fraud, misrepresentation, or security threats.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">12. Privacy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">We collect, store, and process personal and business-related information in accordance with applicable privacy laws. Your use of the Platform signifies your consent to the collection and use of information as described. We do not sell, rent, or share your personal information, mobile phone number, or SMS opt-in data with any third parties or affiliates for marketing or promotional purposes.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">13. Risk Disclaimers.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">By using the Platform, you understand and accept that we&#39;re not responsible for:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Injury, loss, illness, or death of any pet, before, during, or after service.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Emotional distress, economic losses, or reputational harm from interactions on the platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Property damage caused by pets or Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Misrepresentation or lack of qualifications by Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">14. User Conduct Standards.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Users are expected to:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Conduct professional and respectful behavior towards the Vendors and support staff.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Refrain from abusive, discriminatory, unlawful, or fraudulent conduct.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Avoid posting misleading, explicit, or offensive content on the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Provide accurate pet and contact information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Upload copyrighted or proprietary content without permission.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Not attempt to damage, hack, or disrupt the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Not circumvent the Platform for off-app transactions.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Violations of these conduct standards may result in account suspension, removal, or legal action.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">15. Disclaimer of Warranties.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">THE PLATFORM, INCLUDING ALL FEATURES AND SERVICES, IS OFFERED WITHOUT ANY GUARANTEES OR PROMISES OF ANY KIND. TO THE EXTENT PERMITTED BY LAW, ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES ARE DISCLAIMED, INCLUDING ANY WARRANTIES OF PERFORMANCE, FITNESS, MERCHANTABILITY, OR NON-INFRINGEMENT.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">16. Limitation of Liability.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To the fullest extent permitted under applicable law:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	ThePawffy is not liable for the quality, safety, reliability, or outcome of services provided by Vendors.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	We do not assume responsibility for pet injuries, illnesses, losses, or damages resulting from interactions arranged through the Platform.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	In no case shall ThePawffy’s total cumulative liability to you exceed the total amount of fees, if any, that you paid to ThePawffy in the twelve (12) months prior to the event that gave rise to the claim.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">17. Indemnity.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You agree to indemnify, defend, and hold harmless ThePawffy, its officers, affiliates, and employees from any claims, losses, damages, liabilities, penalties, and costs (including reasonable legal fees) resulting from your use of the Platform, your breach of these Terms, or any violation of law or third-party rights.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">18. Reviews and Feedback Policy.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You may submit ratings and reviews of Vendors after a completed service.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Submitted content must be truthful, respectful, and drawn from your actual experience. ThePawffy reserves the right to moderate, remove, or reject any review that violates our standards or appears misleading or defamatory.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">19. Governing Law and Dispute Resolution.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These terms shall be governed by and construed in accordance with the laws of the State of Texas, without regard to any conflict of law provisions. Any dispute or claim shall be resolved through binding arbitration in Harris County, Texas, administered by a recognized arbitration service. Small claims actions may proceed where permitted. By agreeing to these Terms, you waive the right to a jury trial or to participate in any class action proceedings.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">20. Notice to Texas Residents.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If you are located in the State of Texas, you acknowledge and agree that all services are deemed to occur within Texas, and any legal relationship established under these Terms is subject exclusively to Texas law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">21. Class Action Waiver.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">You agree to resolve any dispute with ThePawffy or ITDesks solely on an individual basis. You agree not to pursue or participate in any class, group, or representative action, whether in court or arbitration. Any claim must be pursued separately and may not be combined with those of other individuals.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">22. General.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy may, at its discretion, help facilitate communication or assist with dispute resolution between Users and Vendors. However, ThePawffy is under no obligation to mediate, issue refunds, or enforce Vendor policies unless required by applicable law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">23. Copyright Infringement and Notice.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy respects the proprietary rights of others and expects all users to do the same. If you believe your copyrighted material has been used on the Platform without permission, you must submit a written notice that includes:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Your full name;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	Contact information;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A description of the copyrighted work in question;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A clear reference to the allegedly infringing content and its location on the Platform;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A statement that you believe with certainty the use is unauthorized;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A legally binding declaration, under penalty of perjury, confirming the accuracy of your claim and your authority to represent the owner of the rights;</p>
          <p className="mb-4 text-gray-700 leading-relaxed">•	A physical or electronic signature from you or your authorized representative.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">To send DMCA Notice, contact us at:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Email Address</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy complies with the DMCA and responds in a timely manner to verified takedown requests.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">24. No Copyright License or Waiver.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Nothing in these Terms shall be interpreted as granting any license or right to use any proprietary of ThePawffy or its licensors except as expressly provided. Any unauthorized use of copyrighted materials may result in suspension or termination of access to the Platform, and may be prosecuted under applicable law.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">25. The Pawffy’s Right to Content and Technology.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">All content, branding elements, features, and technology made available through ThePawffy are the sole property of ThePawffy and are protected under applicable laws. Use of the Platform’s features, code, or content without our written approval, including copying, altering, or reverse engineering is strictly prohibited</p>
          <p className="mb-4 text-gray-700 leading-relaxed">26. Modifications.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">ThePawffy reserves the right to modify these Terms periodically. All updates will be posted with the revised effective date. Material changes will be communicated via email or in-app notice. By continuing to use the Platform, you acknowledge and accept the modified Terms.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">27. Severability.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">If any provision of these Terms is determined to be invalid, illegal, or unenforceable under applicable law, that provision shall be modified or limited to the extent necessary to make it enforceable. The remainder of these Terms will remain valid and in full effect.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">28. Entire Agreement.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">These Terms, along with our Privacy Policy, constitute the entire agreement between you and ThePawffy regarding your use of the Platform. No verbal or external communication alters or supersedes these Terms unless executed in writing and signed by both parties.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">29. Contact Information.</p>
          <p className="mb-4 text-gray-700 leading-relaxed">For legal notices or questions, contact us at:</p>
          <p className="mb-4 text-gray-700 leading-relaxed">(Phone Number) legal@thepawffyapp.com</p>
          <p className="mb-4 text-gray-700 leading-relaxed">Address: 5900 Balcones Drive</p>
          <p className="mb-4 text-gray-700 leading-relaxed">STE Austin, TX 78731</p>
        </div>
      </motion.div>
    </div>
  );
};

export default TermsUsers;
